
#include "internal.h"
#include <AL/efx-presets.h>

static EFXEAXREVERBPROPERTIES RPG_Audio_GetReverbProperties(RPG_REVERB_PRESET preset) {
    switch (preset) {
        case RPG_REVERB_PRESET_GENERIC: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_GENERIC;
        case RPG_REVERB_PRESET_PADDEDCELL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PADDEDCELL;
        case RPG_REVERB_PRESET_ROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ROOM;
        case RPG_REVERB_PRESET_BATHROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_BATHROOM;
        case RPG_REVERB_PRESET_LIVINGROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_LIVINGROOM;
        case RPG_REVERB_PRESET_STONEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_STONEROOM;
        case RPG_REVERB_PRESET_AUDITORIUM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_AUDITORIUM;
        case RPG_REVERB_PRESET_CONCERTHALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CONCERTHALL;
        case RPG_REVERB_PRESET_CAVE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CAVE;
        case RPG_REVERB_PRESET_ARENA: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ARENA;
        case RPG_REVERB_PRESET_HANGAR: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_HANGAR;
        case RPG_REVERB_PRESET_CARPETEDHALLWAY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CARPETEDHALLWAY;
        case RPG_REVERB_PRESET_HALLWAY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_HALLWAY;
        case RPG_REVERB_PRESET_STONECORRIDOR: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_STONECORRIDOR;
        case RPG_REVERB_PRESET_ALLEY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ALLEY;
        case RPG_REVERB_PRESET_FOREST: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FOREST;
        case RPG_REVERB_PRESET_CITY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY;
        case RPG_REVERB_PRESET_MOUNTAINS: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_MOUNTAINS;
        case RPG_REVERB_PRESET_QUARRY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_QUARRY;
        case RPG_REVERB_PRESET_PLAIN: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PLAIN;
        case RPG_REVERB_PRESET_PARKINGLOT: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PARKINGLOT;
        case RPG_REVERB_PRESET_SEWERPIPE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SEWERPIPE;
        case RPG_REVERB_PRESET_UNDERWATER: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_UNDERWATER;
        case RPG_REVERB_PRESET_DRUGGED: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRUGGED;
        case RPG_REVERB_PRESET_DIZZY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DIZZY;
        case RPG_REVERB_PRESET_PSYCHOTIC: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PSYCHOTIC;

        /* Castle Presets */
        case RPG_REVERB_PRESET_CASTLE_SMALLROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_SMALLROOM;
        case RPG_REVERB_PRESET_CASTLE_SHORTPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_SHORTPASSAGE;
        case RPG_REVERB_PRESET_CASTLE_MEDIUMROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_MEDIUMROOM;
        case RPG_REVERB_PRESET_CASTLE_LARGEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_LARGEROOM;
        case RPG_REVERB_PRESET_CASTLE_LONGPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_LONGPASSAGE;
        case RPG_REVERB_PRESET_CASTLE_HALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_HALL;
        case RPG_REVERB_PRESET_CASTLE_CUPBOARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_CUPBOARD;
        case RPG_REVERB_PRESET_CASTLE_COURTYARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_COURTYARD;
        case RPG_REVERB_PRESET_CASTLE_ALCOVE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CASTLE_ALCOVE;

        /* Factory Presets */
        case RPG_REVERB_PRESET_FACTORY_SMALLROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_SMALLROOM;
        case RPG_REVERB_PRESET_FACTORY_SHORTPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_SHORTPASSAGE;
        case RPG_REVERB_PRESET_FACTORY_MEDIUMROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_MEDIUMROOM;
        case RPG_REVERB_PRESET_FACTORY_LARGEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_LARGEROOM;
        case RPG_REVERB_PRESET_FACTORY_LONGPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_LONGPASSAGE;
        case RPG_REVERB_PRESET_FACTORY_HALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_HALL;
        case RPG_REVERB_PRESET_FACTORY_CUPBOARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_CUPBOARD;
        case RPG_REVERB_PRESET_FACTORY_COURTYARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_COURTYARD;
        case RPG_REVERB_PRESET_FACTORY_ALCOVE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_FACTORY_ALCOVE;
        /* Ice Palace Presets */
        case RPG_REVERB_PRESET_ICEPALACE_SMALLROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_SMALLROOM;
        case RPG_REVERB_PRESET_ICEPALACE_SHORTPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_SHORTPASSAGE;
        case RPG_REVERB_PRESET_ICEPALACE_MEDIUMROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_MEDIUMROOM;
        case RPG_REVERB_PRESET_ICEPALACE_LARGEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_LARGEROOM;
        case RPG_REVERB_PRESET_ICEPALACE_LONGPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_LONGPASSAGE;
        case RPG_REVERB_PRESET_ICEPALACE_HALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_HALL;
        case RPG_REVERB_PRESET_ICEPALACE_CUPBOARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_CUPBOARD;
        case RPG_REVERB_PRESET_ICEPALACE_COURTYARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_COURTYARD;
        case RPG_REVERB_PRESET_ICEPALACE_ALCOVE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_ICEPALACE_ALCOVE;
        /* Space Station Presets */
        case RPG_REVERB_PRESET_SPACESTATION_SMALLROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_SMALLROOM;
        case RPG_REVERB_PRESET_SPACESTATION_SHORTPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_SHORTPASSAGE;
        case RPG_REVERB_PRESET_SPACESTATION_MEDIUMROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_MEDIUMROOM;
        case RPG_REVERB_PRESET_SPACESTATION_LARGEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_LARGEROOM;
        case RPG_REVERB_PRESET_SPACESTATION_LONGPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_LONGPASSAGE;
        case RPG_REVERB_PRESET_SPACESTATION_HALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_HALL;
        case RPG_REVERB_PRESET_SPACESTATION_CUPBOARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_CUPBOARD;
        case RPG_REVERB_PRESET_SPACESTATION_ALCOVE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPACESTATION_ALCOVE;
        /* Wooden Galleon Presets */
        case RPG_REVERB_PRESET_WOODEN_SMALLROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_SMALLROOM;
        case RPG_REVERB_PRESET_WOODEN_SHORTPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_SHORTPASSAGE;
        case RPG_REVERB_PRESET_WOODEN_MEDIUMROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_MEDIUMROOM;
        case RPG_REVERB_PRESET_WOODEN_LARGEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_LARGEROOM;
        case RPG_REVERB_PRESET_WOODEN_LONGPASSAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_LONGPASSAGE;
        case RPG_REVERB_PRESET_WOODEN_HALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_HALL;
        case RPG_REVERB_PRESET_WOODEN_CUPBOARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_CUPBOARD;
        case RPG_REVERB_PRESET_WOODEN_COURTYARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_COURTYARD;
        case RPG_REVERB_PRESET_WOODEN_ALCOVE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_WOODEN_ALCOVE;
        /* Sports Presets */
        case RPG_REVERB_PRESET_SPORT_EMPTYSTADIUM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_EMPTYSTADIUM;
        case RPG_REVERB_PRESET_SPORT_SQUASHCOURT: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_SQUASHCOURT;
        case RPG_REVERB_PRESET_SPORT_SMALLSWIMMINGPOOL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_SMALLSWIMMINGPOOL;
        case RPG_REVERB_PRESET_SPORT_LARGESWIMMINGPOOL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_LARGESWIMMINGPOOL;
        case RPG_REVERB_PRESET_SPORT_GYMNASIUM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_GYMNASIUM;
        case RPG_REVERB_PRESET_SPORT_FULLSTADIUM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_FULLSTADIUM;
        case RPG_REVERB_PRESET_SPORT_STADIUMTANNOY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SPORT_STADIUMTANNOY;
        /* Prefab Presets */
        case RPG_REVERB_PRESET_PREFAB_WORKSHOP: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PREFAB_WORKSHOP;
        case RPG_REVERB_PRESET_PREFAB_SCHOOLROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PREFAB_SCHOOLROOM;
        case RPG_REVERB_PRESET_PREFAB_PRACTISEROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PREFAB_PRACTISEROOM;
        case RPG_REVERB_PRESET_PREFAB_OUTHOUSE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PREFAB_OUTHOUSE;
        case RPG_REVERB_PRESET_PREFAB_CARAVAN: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PREFAB_CARAVAN;
        /* Dome and Pipe Presets */
        case RPG_REVERB_PRESET_DOME_TOMB: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DOME_TOMB;
        case RPG_REVERB_PRESET_PIPE_SMALL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PIPE_SMALL;
        case RPG_REVERB_PRESET_DOME_SAINTPAULS: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DOME_SAINTPAULS;
        case RPG_REVERB_PRESET_PIPE_LONGTHIN: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PIPE_LONGTHIN;
        case RPG_REVERB_PRESET_PIPE_LARGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PIPE_LARGE;
        case RPG_REVERB_PRESET_PIPE_RESONANT: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_PIPE_RESONANT;
        /* Outdoors Presets */
        case RPG_REVERB_PRESET_OUTDOORS_BACKYARD: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_OUTDOORS_BACKYARD;
        case RPG_REVERB_PRESET_OUTDOORS_ROLLINGPLAINS: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_OUTDOORS_ROLLINGPLAINS;
        case RPG_REVERB_PRESET_OUTDOORS_DEEPCANYON: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_OUTDOORS_DEEPCANYON;
        case RPG_REVERB_PRESET_OUTDOORS_CREEK: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_OUTDOORS_CREEK;
        case RPG_REVERB_PRESET_OUTDOORS_VALLEY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_OUTDOORS_VALLEY;
        /* Mood Presets */
        case RPG_REVERB_PRESET_MOOD_HEAVEN: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_MOOD_HEAVEN;
        case RPG_REVERB_PRESET_MOOD_HELL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_MOOD_HELL;
        case RPG_REVERB_PRESET_MOOD_MEMORY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_MOOD_MEMORY;
        /* Driving Presets */
        case RPG_REVERB_PRESET_DRIVING_COMMENTATOR: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_COMMENTATOR;
        case RPG_REVERB_PRESET_DRIVING_PITGARAGE: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_PITGARAGE;
        case RPG_REVERB_PRESET_DRIVING_INCAR_RACER: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_INCAR_RACER;
        case RPG_REVERB_PRESET_DRIVING_INCAR_SPORTS: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_INCAR_SPORTS;
        case RPG_REVERB_PRESET_DRIVING_INCAR_LUXURY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_INCAR_LUXURY;
        case RPG_REVERB_PRESET_DRIVING_FULLGRANDSTAND: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_FULLGRANDSTAND;
        case RPG_REVERB_PRESET_DRIVING_EMPTYGRANDSTAND: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_EMPTYGRANDSTAND;
        case RPG_REVERB_PRESET_DRIVING_TUNNEL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DRIVING_TUNNEL;
        /* City Presets */
        case RPG_REVERB_PRESET_CITY_STREETS: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY_STREETS;
        case RPG_REVERB_PRESET_CITY_SUBWAY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY_SUBWAY;
        case RPG_REVERB_PRESET_CITY_MUSEUM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY_MUSEUM;
        case RPG_REVERB_PRESET_CITY_LIBRARY: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY_LIBRARY;
        case RPG_REVERB_PRESET_CITY_UNDERPASS: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY_UNDERPASS;
        case RPG_REVERB_PRESET_CITY_ABANDONED: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CITY_ABANDONED;
        /* Misc. Presets */
        case RPG_REVERB_PRESET_DUSTYROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_DUSTYROOM;
        case RPG_REVERB_PRESET_CHAPEL: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_CHAPEL;
        case RPG_REVERB_PRESET_SMALLWATERROOM: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_SMALLWATERROOM;
        default: return (EFXEAXREVERBPROPERTIES)EFX_REVERB_PRESET_GENERIC;
    }
}

static void RPG_Audio_SetReverbPreset(RPGreverb *e, RPG_REVERB_PRESET preset) {
    EFXEAXREVERBPROPERTIES p = RPG_Audio_GetReverbProperties(preset);
    if (e->type == AL_EFFECT_EAXREVERB) {
        // EAX Reverb is only in OpenAL-Soft implementations
        alEffectf(e->effect, AL_EAXREVERB_DENSITY, p.flDensity);
        alEffectf(e->effect, AL_EAXREVERB_DIFFUSION, p.flDiffusion);
        alEffectf(e->effect, AL_EAXREVERB_GAIN, p.flGain);
        alEffectf(e->effect, AL_EAXREVERB_GAINHF, p.flGainHF);
        alEffectf(e->effect, AL_EAXREVERB_GAINLF, p.flGainLF);
        alEffectf(e->effect, AL_EAXREVERB_DECAY_TIME, p.flDecayTime);
        alEffectf(e->effect, AL_EAXREVERB_DECAY_HFRATIO, p.flDecayHFRatio);
        alEffectf(e->effect, AL_EAXREVERB_DECAY_LFRATIO, p.flDecayLFRatio);
        alEffectf(e->effect, AL_EAXREVERB_REFLECTIONS_GAIN, p.flReflectionsGain);
        alEffectf(e->effect, AL_EAXREVERB_REFLECTIONS_DELAY, p.flReflectionsDelay);
        alEffectfv(e->effect, AL_EAXREVERB_REFLECTIONS_PAN, p.flReflectionsPan);
        alEffectf(e->effect, AL_EAXREVERB_LATE_REVERB_GAIN, p.flLateReverbGain);
        alEffectf(e->effect, AL_EAXREVERB_LATE_REVERB_DELAY, p.flLateReverbDelay);
        alEffectfv(e->effect, AL_EAXREVERB_LATE_REVERB_PAN, p.flLateReverbPan);
        alEffectf(e->effect, AL_EAXREVERB_ECHO_TIME, p.flEchoTime);
        alEffectf(e->effect, AL_EAXREVERB_ECHO_DEPTH, p.flEchoDepth);
        alEffectf(e->effect, AL_EAXREVERB_MODULATION_TIME, p.flModulationTime);
        alEffectf(e->effect, AL_EAXREVERB_MODULATION_DEPTH, p.flModulationDepth);
        alEffectf(e->effect, AL_EAXREVERB_AIR_ABSORPTION_GAINHF, p.flAirAbsorptionGainHF);
        alEffectf(e->effect, AL_EAXREVERB_HFREFERENCE, p.flHFReference);
        alEffectf(e->effect, AL_EAXREVERB_LFREFERENCE, p.flLFReference);
        alEffectf(e->effect, AL_EAXREVERB_ROOM_ROLLOFF_FACTOR, p.flRoomRolloffFactor);
        alEffecti(e->effect, AL_EAXREVERB_DECAY_HFLIMIT, p.iDecayHFLimit);
    } else {
        // EAX Reverb not present, use standard reverb
        alEffectf(e->effect, AL_REVERB_DENSITY, p.flDensity);
        alEffectf(e->effect, AL_REVERB_DIFFUSION, p.flDiffusion);
        alEffectf(e->effect, AL_REVERB_GAIN, p.flGain);
        alEffectf(e->effect, AL_REVERB_GAINHF, p.flGainHF);
        alEffectf(e->effect, AL_REVERB_DECAY_TIME, p.flDecayTime);
        alEffectf(e->effect, AL_REVERB_DECAY_HFRATIO, p.flDecayHFRatio);
        alEffectf(e->effect, AL_REVERB_REFLECTIONS_GAIN, p.flReflectionsGain);
        alEffectf(e->effect, AL_REVERB_REFLECTIONS_DELAY, p.flReflectionsDelay);
        alEffectf(e->effect, AL_REVERB_LATE_REVERB_GAIN, p.flLateReverbGain);
        alEffectf(e->effect, AL_REVERB_LATE_REVERB_DELAY, p.flLateReverbDelay);
        alEffectf(e->effect, AL_REVERB_AIR_ABSORPTION_GAINHF, p.flAirAbsorptionGainHF);
        alEffectf(e->effect, AL_REVERB_ROOM_ROLLOFF_FACTOR, p.flRoomRolloffFactor);
        alEffecti(e->effect, AL_REVERB_DECAY_HFLIMIT, p.iDecayHFLimit);
    }
}

RPG_RESULT RPG_Audio_CreateEffect(RPG_AUDIOFX_TYPE type, RPGaudiofx **fx) {
    RPGaudiofx *f = RPG_ALLOC(RPGaudiofx);
    alGenEffects(1, &f->effect);
    alEffecti(f->effect, AL_EFFECT_TYPE, (ALenum) type);
    if (alGetError()) {
        RPG_FREE(f);
        return RPG_ERR_AUDIO_EXT;
    }
    f->type = type;
    *fx = f;
    return RPG_NO_ERROR;
}

RPG_RESULT RPG_Audio_CreateReverb(RPG_REVERB_PRESET preset, RPGreverb **reverb) {
    RPGreverb *r;
    if (RPG_Audio_CreateEffect(AL_EFFECT_EAXREVERB, &r)) {
        return RPG_ERR_AUDIO_EXT;
    }
    RPG_Audio_SetReverbPreset(r, preset);
    *reverb = r;
    return RPG_NO_ERROR;
}

