

const char *RPG_VERTEX_SHADER = "#version 330 core\n"
                                "\n"
                                "layout (location = 0) in vec4 vertex;\n"
                                "\n"
                                "out vec2 coords;\n"
                                "\n"
                                "uniform mat4 model;\n"
                                "uniform mat4 projection;\n"
                                "\n"
                                "void main()\n"
                                "{\n"
                                "    coords = vec2(vertex.zw);\n"
                                "    gl_Position = projection * model * vec4(vertex.xy, 0.0, 1.0);\n"
                                "}";

const char *RPG_FRAGMENT_SHADER = "#version 330 core\n"
                                  "\n"
                                  "in vec2 coords;\n"
                                  "out vec4 result;\n"
                                  "\n"
                                  "uniform sampler2D image;\n"
                                  "uniform vec4 color;\n"
                                  "uniform vec4 tone;\n"
                                  "uniform vec4 flash;\n"
                                  "uniform float alpha;\n"
                                  "uniform float hue;\n"
                                  "\n"
                                  "vec3 hue_shift(vec3 color, float hueAdjust) {\n"
                                  "\n"
                                  "    const vec3 kRGBToYPrime = vec3(0.299, 0.587, 0.114);\n"
                                  "    const vec3 kRGBToI = vec3(0.596, -0.275, -0.321);\n"
                                  "    const vec3 kRGBToQ = vec3(0.212, -0.523, 0.311);\n"
                                  "    const vec3 kYIQToR = vec3(1.0, 0.956, 0.621);\n"
                                  "    const vec3 kYIQToG = vec3(1.0, -0.272, -0.647);\n"
                                  "    const vec3 kYIQToB = vec3(1.0, -1.107, 1.704);\n"
                                  "\n"
                                  "    float YPrime = dot(color, kRGBToYPrime);\n"
                                  "    float I = dot(color, kRGBToI);\n"
                                  "    float Q = dot(color, kRGBToQ);\n"
                                  "    float h = atan(Q, I);\n"
                                  "    float chroma = sqrt(I * I + Q * Q);\n"
                                  "\n"
                                  "    h += radians(hue);\n"
                                  "    Q = chroma * sin(h);\n"
                                  "    I = chroma * cos(h);\n"
                                  "    vec3 yIQ = vec3(YPrime, I, Q);\n"
                                  "    return vec3(dot(yIQ, kYIQToR), dot(yIQ, kYIQToG), dot(yIQ, kYIQToB));\n"
                                  "}\n"
                                  "\n"
                                  "void main() {\n"
                                  "    // TODO: Profile branching vs non-branching \n"
                                  "    result = texture(image, coords);\n"
                                  "    if (hue > 0.0) {\n"
                                  "        result = vec4(hue_shift(result.rgb, hue), result.a);\n"
                                  "    }\n"
                                  "    if (color.a > 0.0) {\n"
                                  "        result = vec4(mix(result.rgb, color.rgb, color.a), result.a);\n"
                                  "    }\n"
                                  "    if (tone.a > 0.0) {\n"
                                  "        float avg = (result.r + result.g + result.b) / 3.0;\n"
                                  "        result.r = result.r - ((result.r - avg) * tone.a);\n"
                                  "        result.g = result.g - ((result.g - avg) * tone.a);\n"
                                  "        result.b = result.b - ((result.b - avg) * tone.a);\n"
                                  "    }\n"
                                  "    result = vec4(clamp(result.rgb + tone.rgb, 0.0, 1.0), result.a);\n"
                                  "\n"
                                  "    if (flash.a > 0.0) {\n"
                                  "        result = vec4(mix(result.rgb, flash.rgb, flash.a), result.a);\n"
                                  "    }\n"
                                  "    if (alpha < 1.0) {\n"
                                  "        result *= alpha;\n"
                                  "    }\n"
                                  "}";

const char *RPG_FONT_VERTEX = "#version 330 core\n"
                              "\n"
                              "layout (location = 0) in vec4 vertex;\n"
                              "out vec2 coords;\n"
                              "\n"
                              "uniform mat4 projection;\n"
                              "\n"
                              "void main()\n"
                              "{\n"
                              "    gl_Position = projection * vec4(vertex.xy, 0.0, 1.0);\n"
                              "    coords = vertex.zw;\n"
                              "} ";

const char *RPG_FONT_FRAGMENT = "#version 330 core\n"
                                "\n"
                                "in vec2 coords;\n"
                                "out vec4 result;\n"
                                "uniform sampler2D text;\n"
                                "uniform vec4 color;\n"
                                "\n"
                                "void main()\n"
                                "{\n"
                                "    result = vec4(1.0, 1.0, 1.0, texture(text, coords).r) * color;\n"
                                "}";